version: "2"

services:

  lava-master:
    hostname: lava-master
    restart: always
    build:
      context: ./lava-master
      args:
        admin_username: "loic"
        admin_password: "password"
        admin_email: "admin@localhost.com"
    ports:
      - "80:80"           # http
      - "5555:5555"       # logger
      - "5556:5556"       # master
    network_mode: "host"
    extra_hosts:
      - "worker0:127.0.0.1" # local-instance

  lava-worker:
    hostname: worker0
    dns: 127.0.0.1
    restart: always
    build:
      context: ./lava-worker
      args:
        board: "db820c"
    volumes:
      - /dev:/dev
      - /boot:/boot
      - /lib/modules:/lib/modules
      - /sys/class/gpio:/sys/class/gpio:rw # Power control via GPIO
      - /tmp:/tmp                          # overlayfs nfs export workaround
      - /var/tmp/:/var/tmp/
      - /var/cache:/var/cache/
      - /sys/fs/cgroup:/sys/fs/cgroup:rw # lxc
      - /sys/devices/virtual/net:/sys/devices/virtual/net:rw # lxc net interface
      - /images:/images:ro # temp, for local image download
    privileged: true
    ports:
      - "69:69"        # tftp
      - "2049:2049"    # nfs4
    network_mode: "host"
    extra_hosts:
      - "lava-master:127.0.0.1" # local-instance

  wifi-tester:
    hostname: wifi-tester
    restart: always
    build:
      context: ./wifi-tester
      args:
        ssid: LAVA_WIFI
        password: lavatest
    privileged: true
    network_mode: "host"

  bluetooth-tester:
    hostname: bluetooth-tester
    restart: always
    build:
      context: ./bluetooth-tester
      args:
        name: LAVA_BT
    privileged: true
    network_mode: "host"

  file-server:
    hostname: file-server
    restart: always
    build:
      context: ./file-server
      args:
        port_http: 8080
        port_ftp: 2121
        root: "/images"
    volumes:
      - /images:/images
    ports:
      - "8080:8080"
      - "2121:2121"
    privileged: true
    network_mode: "host"
