version: "2"
services:
  lava-master:
    hostname: lava-master
    restart: always
    build:
      context: ./
      args:
        admin_username: "admin"
        admin_password: "password"
        admin_email: "admin@localhost.com"
    ports:
      - "80:80"           # http
      - "5555:5555"       # logger
      - "5556:5556"       # master
    network_mode: "host"
    extra_hosts:
      - "worker0:127.0.0.1"
