version: "2"
services:
  lava-slave0:
    hostname: worker0
    restart: always
    build:
      context: ./
    volumes:
      - /dev:/dev
      - /boot:/boot
      - /lib/modules:/lib/modules

networks:
  default:
    external:
      name: lavanet
